/*******************************************************************************
 * Copyright (c) 2010 Verticon, Inc. and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Verticon, Inc. - initial API and implementation
 *******************************************************************************/
package com.verticon.tracker.fair.validation;

import org.eclipse.emf.common.util.EList;

import com.verticon.tracker.fair.Division;
import com.verticon.tracker.fair.Person;

/**
 * A sample validator interface for {@link com.verticon.tracker.fair.Department}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DepartmentValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateClass(EList<com.verticon.tracker.fair.Class> value);

	boolean validateSuperintendent(EList<Person> value);

	boolean validateClasses(EList<com.verticon.tracker.fair.Class> value);

	boolean validateSuperintendents(EList<Person> value);

	boolean validateDivision(Division value);

	boolean validateComments(String value);

	boolean validateDescription(String value);

	boolean validateSuperIntendent(EList<Person> value);
}
