/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_bluetooth_linux_BluetoothStackBlueZ */

#ifndef _Included_com_intel_bluetooth_linux_BluetoothStackBlueZ
#define _Included_com_intel_bluetooth_linux_BluetoothStackBlueZ
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_bluetooth_linux_BluetoothStackBlueZ_NATIVE_LIBRARY_VERSION
#define com_intel_bluetooth_linux_BluetoothStackBlueZ_NATIVE_LIBRARY_VERSION 2000300L
#ifdef __cplusplus
}
#endif
#endif
