/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.verticon.tracker.validation;

import com.verticon.tracker.Animal;
import com.verticon.tracker.Tag;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.verticon.tracker.Premises}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PremisesValidator {
	boolean validate();

	boolean validatePremisesId(String value);
	boolean validateEmailContact(String value);
	boolean validateAnimals(EList<Animal> value);
	boolean validateUnAppliedTags(EList<Tag> value);
}
