/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.verticon.tracker.validation;

import java.util.Date;

import com.verticon.tracker.Tag;

/**
 * A sample validator interface for {@link com.verticon.tracker.Event}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EventValidator {
	boolean validate();

	boolean validateDateTime(Date value);
	boolean validateEventCode(int value);
	boolean validateElectronicallyRead(boolean value);
	boolean validateCorrection(boolean value);
	boolean validateComments(String value);
	boolean validateIdNumber(long value);
	boolean validateTag(Tag value);

	boolean validateId(String value);
}
