/*
 * generated by Xtext
 */
package org.json.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MongoQueryExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.json.ui.internal.MongoQueryActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.json.ui.internal.MongoQueryActivator.getInstance().getInjector("org.json.MongoQuery");
	}
	
}
