/*
* generated by Xtext
*/
package org.json.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MongoQueryOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
