/*******************************************************************************
 * Copyright (c) 2010 Verticon, Inc. and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Verticon, Inc. - initial API and implementation
 *******************************************************************************/
package com.verticon.tracker.validation;

import com.verticon.tracker.Tag;


/**
 * A sample validator interface for {@link com.verticon.tracker.ReplacedTag}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReplacedTagValidator {
	boolean validate();

	boolean validateOldAin(String value);

	boolean validateOldId(String value);

	boolean validateUsainNumberUsedForOldId(boolean value);

	boolean validateOldTag(Tag value);

	boolean validateOldIdAin(boolean value);

	boolean validateOldIdWasAin(boolean value);
}
