/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.verticon.tracker.validation;

import org.eclipse.emf.common.util.EList;

import com.verticon.tracker.Event;

/**
 * A sample validator interface for {@link com.verticon.tracker.Tag}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TagValidator {
	boolean validate();

	boolean validateIdNumber(long value);
	boolean validateUsainNumberUsed(boolean value);
	boolean validateEvents(EList<Event> value);

	boolean validateId(String value);
}
