/*******************************************************************************
 * Copyright (c) 2010 Verticon, Inc. and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Verticon, Inc. - initial API and implementation
 *******************************************************************************/
package com.verticon.tracker.validation;


/**
 * A sample validator interface for FairRegistration.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FairRegistrationValidator {
	boolean validate();

	boolean validateParticipant(String value);
	boolean validateAddress(String value);
	boolean validatePhone(String value);
	boolean validateParent(String value);
	boolean validateClub(String value);

	boolean validateSaleOrder(int value);

	boolean validateExhibit(int value);
}
