/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.verticon.tracker.fair.validation;

import org.eclipse.emf.common.util.EList;

import com.verticon.tracker.Premises;
import com.verticon.tracker.fair.Division;
import com.verticon.tracker.fair.Person;
import com.verticon.tracker.fair.YouthClub;

/**
 * A sample validator interface for {@link com.verticon.tracker.fair.Fair}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FairValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateYouthClubs(EList<YouthClub> value);

	boolean validateYouthClub(EList<YouthClub> value);

	boolean validateDivision(EList<Division> value);

	boolean validateClubs(EList<YouthClub> value);
	boolean validateDivisions(EList<Division> value);
	boolean validatePremises(Premises value);

	boolean validatePeople(EList<Person> value);

	boolean validateComments(String value);

}
