/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.verticon.tracker.validation;

import com.verticon.tracker.OneToTen;

/**
 * A sample validator interface for {@link com.verticon.tracker.Birthing}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BirthingValidator {
	boolean validate();

	boolean validateViability(boolean value);
	boolean validateAssisted(boolean value);
	boolean validateDifficulty(OneToTen value);
}
