/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.verticon.tracker.validation;


/**
 * A sample validator interface for {@link com.verticon.tracker.MilkTest}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MilkTestValidator {
	boolean validate();

	boolean validatePoundsProduced(double value);
	boolean validatePercentButterFat(double value);
	boolean validatePercentProtein(double value);
	boolean validateSomaticCellCounts(int value);
	boolean validateOtherSolids(double value);
}
