/*******************************************************************************
 * Copyright (c) 2010 Verticon, Inc. and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Verticon, Inc. - initial API and implementation
 *******************************************************************************/
package com.verticon.tracker.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import com.verticon.tracker.Animal;
import com.verticon.tracker.AnimalType;
import com.verticon.tracker.Sex;
import com.verticon.tracker.Tag;
import com.verticon.tracker.util.Age;
import com.verticon.tracker.util.CalendarDateDuration;

/**
 * A sample validator interface for {@link com.verticon.tracker.Animal}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnimalValidator {
	boolean validate();

	boolean validateBirthDate(Date value);
	boolean validateSex(Sex value);
	boolean validateTags(EList<Tag> value);
	boolean validateSpecies(String value);
	boolean validateIdNumber(long value);
	boolean validateBreed(String value);
	boolean validateAge(Age value);

	boolean validateAge(CalendarDateDuration value);
	boolean validateSexCode(String value);
	boolean validateSpeciesCode(String value);

	boolean validateId(String value);

	boolean validateComments(String value);

	boolean validateLastEventDateTime(Date value);

	boolean validateDam(Animal value);

	boolean validateSire(Animal value);

	boolean validateWeight(Integer value);

	boolean validateWeightGainPerDay(Double value);

	boolean validateType(AnimalType value);

	boolean validateVisualID(String value);

	boolean validateAgeInDays(int value);

	boolean validateWeightGainPerDay(Integer value);

	boolean validateWeight(int value);

	boolean validateLastEventDate(Date value);
}
