/*
* generated by Xtext
*/
package org.json.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.json.services.MongoQueryGrammarAccess;

public class MongoQueryParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MongoQueryGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.json.parser.antlr.internal.InternalMongoQueryParser createParser(XtextTokenStream stream) {
		return new org.json.parser.antlr.internal.InternalMongoQueryParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Selector";
	}
	
	public MongoQueryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MongoQueryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
