/*
 * generated by Xtext
 */
package org.json;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MongoQueryRuntimeModule extends org.json.AbstractMongoQueryRuntimeModule {

}
